// AUTOGENERATED FILE - DO NOT MODIFY!

package com.ruturaj.huawei.sayhelloworld

import scala.collection.JavaConverters._
import scala.concurrent.{Future, Promise}

package object implicits {
    class LedgerCoreWrappedException(val code: ErrorCode, message: String) extends Exception(message)
    private def wrapLedgerCoreError(error: com.ruturaj.huawei.sayhelloworld.Error): LedgerCoreWrappedException = {
        error.getCode match {
        }
    }
    private def arrayList2Array[T](a: Array[T]): java.util.ArrayList[T] = new java.util.ArrayList[T](a.toList.asJava.asInstanceOf[java.util.Collection[T]])
    implicit class RichISayHello(val self: ISayHello) {
    }
}
