// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from say_hello_world.djinni

#include "ISayHello.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

ISayHello::ISayHello() : ::djinni::JniInterface<::ISayHello, ISayHello>("com/ruturaj/huawei/sayhelloworld/ISayHello$CppProxy") {}

ISayHello::~ISayHello() = default;


CJNIEXPORT void JNICALL Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ISayHello>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_ruturaj_huawei_sayhelloworld_ISayHello_NewInstance(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ISayHello::NewInstance();
        return ::djinni::release(::djinni_generated::ISayHello::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1getHelloWorld(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ISayHello>(nativeRef);
        auto r = ref->get_hello_world();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1addSayHelloListener(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_listener)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ISayHello>(nativeRef);
        ref->addSayHelloListener(::djinni::I64::toCpp(jniEnv, j_listener));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1removeSayHelloListener(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jboolean j_listener)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ISayHello>(nativeRef);
        ref->removeSayHelloListener(::djinni::Bool::toCpp(jniEnv, j_listener));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1sayHello(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_from, jstring j_to)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ISayHello>(nativeRef);
        ref->sayHello(::djinni::String::toCpp(jniEnv, j_from),
                      ::djinni::String::toCpp(jniEnv, j_to));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
