//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from info.djinni
//
//#pragma once
//
//// #include "support_lib/include/jni_/djinni_support.hpp"
//#include "header/Gender.h"
//#include <aki/jsbind.h>
//
//namespace djinni_generated {
//
//class JNIGender {
//public:
//    using CppType = ::test::hello::Gender;
//    //        using JniType = int;
//
//    using Boxed = JNIGender;
//
//    //    static CppType toCpp(JNIEnv *jniEnv, JniType j) {
//    //        return static_cast<CppType>(::djinni::JniClass<JNIGender>::get().ordinal(jniEnv, j));
//    //    }
//    //
//    //    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, CppType c) {
//    //        return ::djinni::JniClass<JNIGender>::get().create(jniEnv, static_cast<jint>(c));
//    //    }
//
//    CppType toCpp(int j) { return static_cast<CppType>(j); }
//
//    int fromCpp(CppType c) { return static_cast<int>(c); }
//
//private:
//    //        JNIGender() : JniEnum("com/ruturaj/huawei/isayhello/Gender") {}
//    //
//    //        friend ::djinni::JniClass<JNIGender>;
//};
//
////JSBIND_CLASS(JNIGender) {
////    JSBIND_CONSTRUCTOR<>();
////    JSBIND_METHOD(toCpp);
////    JSBIND_METHOD(fromCpp);
////}
////
////JSBIND_ADDON(entry);
//
//} // namespace djinni_generated