//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from info.djinni
//
//#include "JNIISayHello.h" // my header
//#include "JNIMyRecord.h"
//#include "header/ISayHello.h"
//#include "header/MyRecord.h"
//#include <bits/alltypes.h>
//#include <cstdint>
//#include <string>
//#include <iostream>
//#include <hilog/log.h>
//// #include "support_lib/include/jni_/Marshal.hpp"
//
//namespace djinni_generated {
//
////    JNIISayHello::JNIISayHello() : ::djinni::JniInterface<::test::hello::ISayHello, JNIISayHello>(
////            "com/ruturaj/huawei/isayhello/ISayHello$CppProxy") {}
////
//JNIISayHello::~JNIISayHello() = default;
//
//
//void nativeDestroy(std::int64_t nativeRef) {
//    /*try {
//        //        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        //        delete reinterpret_cast<::djinni::CppProxyHandle<::test::hello::ISayHello> *>(nativeRef);
//        std::shared_ptr<test::hello::ISayHello> instance = djinni_generated::JNIISayHello::fromCpp(nativeRef);
//        delete reinterpret_cast<::test::hello::ISayHello *>(nativeRef);
//    }
//    //    JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
//    catch (std::string str) {
//    }*/
//
//    OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_DOMAIN, "RRR", "nativeDestroy");
//}
//
//std::string native_sayHello(int64_t nativeRef, test::hello::MyRecord j_testInfo) {
//    /*try {
//        //        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        //        const auto &ref = ::djinni::objectFromHandleAddress<::test::hello::ISayHello>(nativeRef);
//        //        auto r = ref->sayHello(::djinni_generated::JNIMyRecord::toCpp(jniEnv, j_testInfo));
//        //        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
//        const auto &ref = djinni_generated::JNIISayHello::fromCpp(nativeRef);
//        test::hello::MyRecord testInfo = ref->djinni_generated::JNIISayHello::toCpp(j_testInfo);
//        std::string result = ref->sayHello(testInfo);
//        return result;
//    }
//    //    JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0     *//* value doesn't matter  )
//    catch (std::string str) {
//        return "";
//    }*/
//    auto f = aki::JSBind::GetJSFunction("new CppProxy().native_sayHello");
//    auto value = f->Invoke<char *>();
//    OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_DOMAIN, "RRR", "sayHello");
//    return "sayHello";
//}
//
//std::shared_ptr<test::hello::ISayHello> newInstance() {
//    /*try {
//        //        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
//        //        auto r = ::test::hello::ISayHello::NewInstance();
//        //        return ::djinni::release(::djinni_generated::JNIISayHello::fromCpp(jniEnv, r));
//        std::shared_ptr<test::hello::ISayHello> instance = test::hello::ISayHello::NewInstance();
//        return instance;
//    }
//    //    JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 */
//    /* value doesn't matter */ /*)
//catch (std::string str) {
//return nullptr;
//}*/
//    auto f = aki::JSBind::GetJSFunction("CppProxy.newInstance");
//    auto value = f->Invoke<char *>();
//    OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_DOMAIN, "RRR", "newInstance");
//    return nullptr;
//}
//
//JSBIND_GLOBAL() {
//    JSBIND_FUNCTION(nativeDestroy);
//    JSBIND_FUNCTION(native_sayHello);
//    JSBIND_FUNCTION(newInstance);
//}
//
//JSBIND_ADDON(entry)
//
//} // namespace djinni_generated
