//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from info.djinni
//
//#pragma once
//
//// #include "support_lib/include/jni_/djinni_support.hpp"
//#include "header/ISayHello.h"
//#include "header/MyRecord.h"
//#include <bits/alltypes.h>
//#include <optional>
//#include <aki/jsbind.h>
//
//namespace djinni_generated {
//
//class JavaProxy {
//public:
//    int64_t handle;
//};
//
//class JNIISayHello {
//public:
//    using CppType = std::shared_ptr<::test::hello::ISayHello>;
//    using CppOptType = std::shared_ptr<::test::hello::ISayHello>;
//    //    using JniType = jobject;
//
//    using Boxed = JNIISayHello;
//
//    ~JNIISayHello();
//
//    //        static CppType toCpp(JNIEnv *jniEnv, JniType j) {
//    //            return ::djinni::JniClass<JNIISayHello>::get()._fromJava(jniEnv, j);
//    //        }
//    //
//    //        static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) {
//    //            return {jniEnv, ::djinni::JniClass<JNIISayHello>::get()._toJava(jniEnv, c)};
//    //        }
//    //
//    //        static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv,
//    //        c); }
//
//    /*static std::shared_ptr<test::hello::ISayHello> _toJava(const std::shared_ptr<test::hello::ISayHello> &c) {
//     if (!c) {
//         return nullptr;
//     }
//
//     JavaProxy *proxy = new JavaProxy();
//     proxy->handle = reinterpret_cast<test::hello::ISayHello>(c.get());
//
//     std::shared_ptr<test::hello::ISayHello> javaObject = nullptr;
//     if (auto *proxy = dynamic_cast<JavaProxy *>(c.get())) {
//         // If c is actually a JavaProxy, use its handle to create a new jobject
//         // Replace with your actual jobject creation logic
//         javaObject = createJObjectUsingProxyHandle( proxy->handle);
//     }
//
//     return javaObject;
// }
//
// // Simplified version of _fromJava for illustration purposes
// static std::shared_ptr<test::hello::ISayHello> _fromJava(test::hello::MyRecord j) {
//     if (!j) {
//         return nullptr;
//     }
//
//     JavaProxy *proxy = nullptr;
//     if (auto *javaProxy = j.id) {
//         // If the retrieved jobject is a JavaProxy, assign it to the proxy pointer
//         proxy = javaProxy;
//     }
//
//     std::shared_ptr<test::hello::ISayHello> cppObject =
//         std::shared_ptr<test::hello::ISayHello>(reinterpret_cast<test::hello::ISayHello *>(proxy->handle));
//
//     return cppObject;
// }*/
//
//   /* static std::shared_ptr<test::hello::ISayHello> _fromJava(test::hello::MyRecord j) {
//        // Extract data from j to construct ISayHello instance
//        return std::make_shared<test::hello::ISayHello>(j);
//    }
//
//    static std::shared_ptr<test::hello::ISayHello> _toJava(const CppOptType &c) {
//        // Get data from c to populate MyRecord
//        test::hello::MyRecord j(1, "", "", test::hello::Gender::Man);
//        j.name = c->getName();
//        // ...
//        return j;
//    }
//
//    static std::shared_ptr<test::hello::ISayHello> toCpp(test::hello::MyRecord j) { return _fromJava(j); }
//
//    static std::shared_ptr<test::hello::ISayHello> fromCppOpt(const CppOptType &c) { return _toJava(c); }
//
//    static std::shared_ptr<test::hello::ISayHello> fromCpp(const CppType &c) { return fromCppOpt(c); }*/
//
//    //    static std::shared_ptr<test::hello::ISayHello> toCpp(int j) { return std::make_shared<CppType>(j); }
//    //
//    //    static int getIntVal(const std::shared_ptr<test::hello::ISayHello> &obj) {
//    //        test::hello::MyRecord record(1, "Test", "Project", test::hello::Gender::Man);
//    //        if (obj->sayHello(record) == "Hello") {
//    //            return 1;
//    //        } else {
//    //            return 2;
//    //        }
//    //    }
//    //
//    //    static std::optional<int> fromCppOpt(const CppOptType &c) {
//    //        if (c) {
//    //            return getIntVal(*c);
//    //        }
//    //        return std::nullopt;
//    //    }
//    //
//    //    static std::shared_ptr<test::hello::ISayHello> fromCpp(const std::shared_ptr<test::hello::ISayHello> &c) {
//    //        return fromCppOpt(c);
//    //    }
//
//private:
//    JNIISayHello();
//
//    //    friend ::djinni::JniClass<JNIISayHello>;
//    //    friend ::djinni::JniInterface<::test::hello::ISayHello, JNIISayHello>;
//};
//
//// JSBIND_CLASS(JNIISayHello) {
////     JSBIND_CONSTRUCTOR<>();
////     JSBIND_METHOD(toCpp);
////     JSBIND_METHOD(fromCpp);
//// }
////
//// JSBIND_ADDON(entry);
//
//} // namespace djinni_generated
