//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from info.djinni
//
//#include "JNIMyRecord.h" // my header
//#include "JNIGender.h"
//// #include "support_lib/include/jni_/Marshal.hpp"
//
//namespace djinni_generated {
//
//JNIMyRecord::JNIMyRecord() = default;
//
//JNIMyRecord::~JNIMyRecord() = default;
//
///*auto JNIMyRecord::fromCpp(const CppType &c) {
//    const auto &data = ::djinni::JniClass<JNIMyRecord>::get();
//    auto r = ::djinni::LocalRef<JniType>{
//        jniEnv->NewObject(data.clazz.get(), data.jconstructor, ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.id)),
//                          ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)),
//                          ::djinni::get(::djinni::String::fromCpp(jniEnv, c.project)),
//                          ::djinni::get(::djinni_generated::JNIGender::fromCpp(jniEnv, c.sex)))};
//    ::djinni::jniExceptionCheck(jniEnv);
//    return r;
//}
//
//auto JNIMyRecord::toCpp(JniType j) {
//    ::djinni::JniLocalScope jscope(jniEnv, 5);
//    assert(j != nullptr);
//    const auto &data = ::djinni::JniClass<JNIMyRecord>::get();
//    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_id)),
//            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_name)),
//            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_project)),
//            ::djinni_generated::JNIGender::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_sex))};
//}*/
//
//} // namespace djinni_generated
