//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from info.djinni
//
//#pragma once
//
////#include "support_lib/include/jni_/djinni_support.hpp"
//#include "header/MyRecord.h"
//
//namespace djinni_generated {
//
//    class JNIMyRecord final {
//    public:
//        using CppType = ::test::hello::MyRecord;
////        using JniType = jobject;
//
//        using Boxed = JNIMyRecord;
//
//        ~JNIMyRecord();
//
////        static CppType toCpp(JNIEnv *jniEnv, JniType j);
////
////        static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c);
//
//    private:
//        JNIMyRecord();
//
////        friend ::djinni::JniClass<JNIMyRecord>;
////
////        const ::djinni::GlobalRef<jclass> clazz{
////                ::djinni::jniFindClass("com/ruturaj/huawei/isayhello/MyRecord")};
////        const jmethodID jconstructor{::djinni::jniGetMethodID(clazz.get(), "<init>",
////                                                              "(ILjava/lang/String;Ljava/lang/String;Lcom/ruturaj/huawei/isayhello/Gender;)V")};
////        const jfieldID field_id{::djinni::jniGetFieldID(clazz.get(), "id", "I")};
////        const jfieldID field_name{
////                ::djinni::jniGetFieldID(clazz.get(), "name", "Ljava/lang/String;")};
////        const jfieldID field_project{
////                ::djinni::jniGetFieldID(clazz.get(), "project", "Ljava/lang/String;")};
////        const jfieldID field_sex{
////                ::djinni::jniGetFieldID(clazz.get(), "sex",
////                                        "Lcom/ruturaj/huawei/isayhello/Gender;")};
//    };
//
//}  // namespace djinni_generated
