// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from say_hello_world.djinni

#ifndef DJINNI_GENERATED_NODEISAYHELLO_HPP
#define DJINNI_GENERATED_NODEISAYHELLO_HPP


#include <cstdint>
#include <memory>
#include <string>

#include <nan.h>
#include <node.h>
#include "target/sayhelloworld/cpp/ISayHello.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace ;

class NodeISayHello final {
public:

    static void Initialize(Local<Object> target);
    NodeISayHello() = delete;

    static Local<Object> wrap(const std::shared_ptr<::ISayHello> &object);
    static Nan::Persistent<ObjectTemplate> ISayHello_prototype;

private:
    static NAN_METHOD(NewInstance);

    static NAN_METHOD(get_hello_world);

    static NAN_METHOD(addSayHelloListener);

    static NAN_METHOD(removeSayHelloListener);

    static NAN_METHOD(sayHello);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
};
#endif //DJINNI_GENERATED_NODEISAYHELLO_HPP
