// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from say_hello_world.djinni

#include "NodeISayHelloCpp.hpp"
#include "NodeObjectWrapper.hpp"
#include "NodeHexUtils.hpp"

using namespace v8;
using namespace node;
using namespace std;

NAN_METHOD(NodeISayHello::addSayHelloListener) {

    //Check if method called with right number of arguments
    if(info.Length() != 1)
    {
        return Nan::ThrowError("NodeISayHello::addSayHelloListener needs 1 arguments");
    }

    //Check if parameters have correct types
    auto arg_0 = Nan::To<int64_t>(info[0]).FromJust();

    //Unwrap current object and retrieve its Cpp Implementation
    auto cpp_impl = djinni::js::ObjectWrapper<::ISayHello>::Unwrap(info.This());
    if(!cpp_impl)
    {
        return Nan::ThrowError("NodeISayHello::addSayHelloListener : implementation of ISayHello is not valid");
    }
    cpp_impl->addSayHelloListener(arg_0);
}
NAN_METHOD(NodeISayHello::removeSayHelloListener) {

    //Check if method called with right number of arguments
    if(info.Length() != 1)
    {
        return Nan::ThrowError("NodeISayHello::removeSayHelloListener needs 1 arguments");
    }

    //Check if parameters have correct types
    auto arg_0 = Nan::To<bool>(info[0]).FromJust();

    //Unwrap current object and retrieve its Cpp Implementation
    auto cpp_impl = djinni::js::ObjectWrapper<::ISayHello>::Unwrap(info.This());
    if(!cpp_impl)
    {
        return Nan::ThrowError("NodeISayHello::removeSayHelloListener : implementation of ISayHello is not valid");
    }
    cpp_impl->removeSayHelloListener(arg_0);
}
NAN_METHOD(NodeISayHello::sayHello) {

    //Check if method called with right number of arguments
    if(info.Length() != 2)
    {
        return Nan::ThrowError("NodeISayHello::sayHello needs 2 arguments");
    }

    //Check if parameters have correct types
    Nan::Utf8String string_arg_0(info[0]->ToString(Nan::GetCurrentContext()).ToLocalChecked());
    auto arg_0 = std::string(*string_arg_0);
    Nan::Utf8String string_arg_1(info[1]->ToString(Nan::GetCurrentContext()).ToLocalChecked());
    auto arg_1 = std::string(*string_arg_1);

    //Unwrap current object and retrieve its Cpp Implementation
    auto cpp_impl = djinni::js::ObjectWrapper<::ISayHello>::Unwrap(info.This());
    if(!cpp_impl)
    {
        return Nan::ThrowError("NodeISayHello::sayHello : implementation of ISayHello is not valid");
    }
    cpp_impl->sayHello(arg_0,arg_1);
}

NAN_METHOD(NodeISayHello::New) {
    //Only new allowed
    if(!info.IsConstructCall())
    {
        return Nan::ThrowError("NodeISayHello function can only be called as constructor (use New)");
    }
    info.GetReturnValue().Set(info.This());
}


Nan::Persistent<ObjectTemplate> NodeISayHello::ISayHello_prototype;

Local<Object> NodeISayHello::wrap(const std::shared_ptr<::ISayHello> &object) {
    Nan::EscapableHandleScope scope;
    Local<ObjectTemplate> local_prototype = Nan::New(ISayHello_prototype);

    Local<Object> obj;
    if(!local_prototype.IsEmpty())
    {
        obj = local_prototype->NewInstance(Nan::GetCurrentContext()).ToLocalChecked();
        djinni::js::ObjectWrapper<::ISayHello>::Wrap(object, obj);
    }
    else
    {
        Nan::ThrowError("NodeISayHello::wrap: object template not valid");
    }
    return scope.Escape(obj);
}

NAN_METHOD(NodeISayHello::isNull) {
    auto cpp_implementation = djinni::js::ObjectWrapper<::ISayHello>::Unwrap(info.This());
    auto isNull = !cpp_implementation ? true : false;
    return info.GetReturnValue().Set(Nan::New<Boolean>(isNull));
}

void NodeISayHello::Initialize(Local<Object> target) {
    Nan::HandleScope scope;

    Local<FunctionTemplate> func_template = Nan::New<FunctionTemplate>(NodeISayHello::New);
    Local<ObjectTemplate> objectTemplate = func_template->InstanceTemplate();
    objectTemplate->SetInternalFieldCount(1);

    func_template->SetClassName(Nan::New<String>("NodeISayHello").ToLocalChecked());

    //SetPrototypeMethod all methods
    Nan::SetPrototypeMethod(func_template,"addSayHelloListener", addSayHelloListener);
    Nan::SetPrototypeMethod(func_template,"removeSayHelloListener", removeSayHelloListener);
    Nan::SetPrototypeMethod(func_template,"sayHello", sayHello);
    Nan::SetPrototypeMethod(func_template,"isNull", isNull);
    //Set object prototype
    ISayHello_prototype.Reset(objectTemplate);

    //Add template to target
    Nan::Set(target, Nan::New<String>("NodeISayHello").ToLocalChecked(), Nan::GetFunction(func_template).ToLocalChecked());
}
