// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

#include <nan.h>
#include <node.h>

#include "NodeISayHelloCpp.hpp"

using namespace v8;
using namespace node;

static void initAll(Local<Object> target)
{
    Nan::HandleScope scope;
    NodeISayHello::Initialize(target);
}
NODE_MODULE(QQNT,initAll);
