// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

declare class NodeISayHello
{
    declare function addSayHelloListener(listener: number);
    declare function removeSayHelloListener(listener: boolean);
    declare function sayHello(from: string, to: string);
}
