//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from say_hello_world.djinni
//
//#include <string.h>
//#include <jni.h>
//#include <string>
//#include <mutex>
//#include <cassert>
//#include <cassert>
//#include <exception>
//#include <memory>
//#include <mutex>
//#include <string>
//#include <vector>
//#include <jni.h>
//
//#ifndef DJINNI_GENERATED_ISAYHELLO_HPP_JNI_
//#define DJINNI_GENERATED_ISAYHELLO_HPP_JNI_
//
//#define CJNIEXPORT extern "C" JNIEXPORT
//
//#include "-ISayHello_.hpp"
////#include "djinni_support.hpp"
////
////namespace djinni_generated {
//
//void jniExceptionCheck(JNIEnv *env);
//
//JNIEnv *jniGetThreadEnv();
//
////struct JavaIdentityHash;
////struct JavaIdentityEquals;
////struct JavaProxyCacheTraits {
////    using UnowningImplPointer = jobject;
////    using OwningImplPointer = jobject;
////    using OwningProxyPointer = std::shared_ptr<void>;
////    using WeakProxyPointer = std::weak_ptr<void>;
////    using UnowningImplPointerHash = JavaIdentityHash;
////    using UnowningImplPointerEqual = JavaIdentityEquals;
////};
////extern class JavaProxyCacheTraits;
////using JavaProxyCache = JavaProxyCacheTraits;
////template <typename T> using JavaProxyHandle = GlobalRef<jobject>;
////
////class JavaWeakRef;
////struct JniCppProxyCacheTraits {
////    using UnowningImplPointer = void *;
////    using OwningImplPointer = std::shared_ptr<void>;
////    using OwningProxyPointer = jobject;
////    using WeakProxyPointer = JavaWeakRef;
////    using UnowningImplPointerHash = std::hash<void *>;
////    using UnowningImplPointerEqual = std::equal_to<void *>;
////};
////extern template class ProxyCache<JniCppProxyCacheTraits>;
////using JniCppProxyCache = ProxyCache<JniCppProxyCacheTraits>;
////template <class T> using CppProxyHandle = JniCppProxyCache::Handle<std::shared_ptr<T>>;
//
//class JniClassInitializer {
//
//    using registration_vec = std::vector<std::function<void()>>;
//
//    static registration_vec get_all();
//
//private:
//
//    template<class C> friend
//    class JniClass;
//
//    friend void jniInit(JavaVM *);
//
//    static registration_vec &get_vec();
//
//    static std::mutex &get_mutex();
//
//public:
//    JniClassInitializer(std::function<void()> init);
//};
//
//template<class C>
//class JniClass {
//public:
//    static const C &get() {
//        (void) s_initializer; // ensure that initializer is actually instantiated
//        assert(s_singleton);
//        return *s_singleton;
//    }
//
//private:
//    static const JniClassInitializer s_initializer;
//    static std::unique_ptr<C> s_singleton;
//
//    static void allocate() {
//        // We can't use make_unique here, because C will have a private constructor and
//        // list JniClass as a friend; so we have to allocate it by hand.
//        s_singleton = std::unique_ptr<C>(new C());
//    }
//};
//
//struct CppProxyClassInfo {
//    const jclass clazz;
//    const jmethodID constructor;
//    const jfieldID idField;
//
//    CppProxyClassInfo(const char *className);
//
//    CppProxyClassInfo();
//
//    ~CppProxyClassInfo();
//
//    // Validity check
//    explicit operator bool() const { return bool(clazz); }
//};
//
//template<class I, class Self>
//class JniInterface {
//public:
//    /*
//     * Given a C++ object, find or create a Java version. The cases here are:
//     * 1. Null
//     * 2. The provided C++ object is actually a JavaProxy (C++-side proxy for Java impl)
//     * 3. The provided C++ object has an existing CppProxy (Java-side proxy for C++ impl)
//     * 4. The provided C++ object needs a new CppProxy allocated
//     */
//    jobject _toJava(JNIEnv *jniEnv, const std::shared_ptr<I> &c) const {
//        // Case 1 - null
//        if (!c) {
//            return nullptr;
//        }
//
//        // Case 2 - already a JavaProxy. Only possible if Self::JavaProxy exists.
//        if (jobject impl = _unwrapJavaProxy<Self>(&c)) {
//            return jniEnv->NewLocalRef(impl);
//        }
//
////         Cases 3 and 4.
//        assert(m_cppProxyClass);
//        int newCppProxy;
//        return get(typeid(c), c, &newCppProxy);
//
//    }
//
//    /*
//     * Given a Java object, find or create a C++ version. The cases here are:
//     * 1. Null
//     * 2. The provided Java object is actually a CppProxy (Java-side proxy for a C++ impl)
//     * 3. The provided Java object has an existing JavaProxy (C++-side proxy for a Java impl)
//     * 4. The provided Java object needs a new JavaProxy allocated
//     */
//    std::shared_ptr<I> _fromJava(JNIEnv *jniEnv, jobject j) const {
//        // Case 1 - null
//        if (!j) {
//            return nullptr;
//        }
//
//        // Case 2 - already a Java proxy; we just need to pull the C++ impl out. (This case
//        // is only possible if we were constructed with a cppProxyClassName parameter.)
//        if (m_cppProxyClass
//            && jniEnv->IsSameObject(jniEnv->GetObjectClass(j), m_cppProxyClass.clazz.get())) {
//            jlong handle = jniEnv->GetLongField(j, m_cppProxyClass.idField);
//            jniExceptionCheck(jniEnv);
//            return objectFromHandleAddress<I>(handle);
//        }
//
//        // Cases 3 and 4 - see _getJavaProxy helper below. JavaProxyCache is responsible for
//        // distinguishing between the two cases. Only possible if Self::JavaProxy exists.
//        return _getJavaProxy<Self>(j);
//    }
//
//    // Constructor for interfaces for which a Java-side CppProxy class exists
//    JniInterface(const char *cppProxyClassName) : m_cppProxyClass(cppProxyClassName) {}
//
//    // Constructor for interfaces without a Java proxy class
//    JniInterface() : m_cppProxyClass{} {}
//
////
////private:
////    /*
////     * Helpers for _toJava above. The possibility that an object is already a C++-side proxy
////     * only exists if the code generator emitted one (if Self::JavaProxy exists).
////     */
////    template <typename S, typename JavaProxy = typename S::JavaProxy>
////    jobject _unwrapJavaProxy(const std::shared_ptr<I> * c) const {
////        if (auto proxy = dynamic_cast<JavaProxy *>(c->get())) {
////            return proxy->template JavaProxyHandle<JavaProxy>::get().get();
////        } else {
////            return nullptr;
////        }
////    }
////
////    template <typename S>
////    jobject _unwrapJavaProxy(...) const {
////        return nullptr;
////    }
////
////    /*
////     * Helper for _toJava above: given a C++ object, allocate a CppProxy on the Java side for
////     * it. This is actually called by jniCppProxyCacheGet, which holds a lock on the global
////     * C++-to-Java proxy map object.
////     */
////    static std::pair<jobject, void*> newCppProxy(const std::shared_ptr<void> & cppObj) {
////        const auto & data = JniClass<Self>::get();
////        const auto & jniEnv = jniGetThreadEnv();
////        std::unique_ptr<CppProxyHandle<I>> to_encapsulate(
////                new CppProxyHandle<I>(std::static_pointer_cast<I>(cppObj)));
////        jlong handle = static_cast<jlong>(reinterpret_cast<uintptr_t>(to_encapsulate.get()));
////        jobject cppProxy = jniEnv->NewObject(data.m_cppProxyClass.clazz.get(),
////                                             data.m_cppProxyClass.constructor,
////                                             handle);
////        jniExceptionCheck(jniEnv);
////        to_encapsulate.release();
////        return { cppProxy, cppObj.get() };
////    }
////
////    /*
////     * Helpers for _fromJava above. We can only produce a C++-side proxy if the code generator
////     * emitted one (if Self::JavaProxy exists).
////     */
////    template <typename S, typename JavaProxy = typename S::JavaProxy>
////    std::shared_ptr<I> _getJavaProxy(jobject j) const {
////        static_assert(std::is_base_of<JavaProxyHandle<JavaProxy>, JavaProxy>::value,
////                      "JavaProxy must derive from JavaProxyCacheEntry");
////
////        return std::static_pointer_cast<JavaProxy>(JavaProxyCache::get(
////                typeid(JavaProxy), j,
////                [] (const jobject & obj) -> std::pair<std::shared_ptr<void>, jobject> {
////                    auto ret = std::make_shared<JavaProxy>(obj);
////                    return { ret, ret->JavaProxyHandle<JavaProxy>::get().get() };
////                }
////        ));
////    }
////
////    template <typename S>
////    std::shared_ptr<I> _getJavaProxy(...) const {
////        assert(false);
////        return nullptr;
////    }
////
//    const CppProxyClassInfo m_cppProxyClass;
//};
//
//class ISayHello_ {
//public:
//    using CppType = std::shared_ptr<::ISayHello_>;
//    using CppOptType = std::shared_ptr<::ISayHello_>;
//    using JniType = jobject;
//
//    using Boxed = ISayHello_;
//
//    ISayHello__();
//
//    static CppType toCpp(JNIEnv *jniEnv, JniType j) {
//        return ::JniClass<ISayHello_>::get()._fromJava(jniEnv, j);
//    }
//
//    static JniType fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) {
//        return {jniEnv, ::JniClass<ISayHello_>::get()._toJava(jniEnv, c)};
//    }
//
//    static JniType fromCpp(JNIEnv *jniEnv, const CppType &c) {
//        return fromCppOpt(jniEnv, c);
//    }
//
//    ISayHello_();
//
//private:
//
//    friend ISayHello_;
//    friend ::ISayHello_;
//
//};
//
////}  // namespace djinni_generated
//#endif //DJINNI_GENERATED_ISAYHELLO_HPP_JNI_
