// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from say_hello_world.djinni

#include "ISayHello.hpp"  // my header
#include "Marshal.hpp"
#include "android/log.h"

namespace djinni_generated {

    ISayHello::ISayHello() : ::djinni::JniInterface<::TEST::TestISayHello, ISayHello>(
            "com/ruturaj/huawei/sayhelloworld/ISayHello$CppProxy") {}

    ISayHello::~ISayHello() = default;


    CJNIEXPORT void JNICALL
    Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_nativeDestroy(JNIEnv *jniEnv,
                                                                                jobject /*this*/,
                                                                                jlong nativeRef) {
        try {
            DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
            delete reinterpret_cast<::djinni::CppProxyHandle<::TEST::TestISayHello> *>(nativeRef);
        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
    }

//    CJNIEXPORT jobject JNICALL
//    Java_com_ruturaj_huawei_sayhelloworld_ISayHello_newInstance(JNIEnv *jniEnv,
//                                                                jclass clazz) {
//        __android_log_print(ANDROID_LOG_ERROR, "RRR:: ", "%s", "NewInstance Implementation 2");
//        try {
//            DJINNI_FUNCTION_PROLOGUE0(jniEnv);
//            auto r = ::TEST::TestISayHello::newInstance();
//            __android_log_print(ANDROID_LOG_ERROR, "RRR::: ", "%s", "NewInstance Implementation 3");
//            return ::djinni::release(::djinni_generated::ISayHello::fromCpp(jniEnv, r));
//        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
//    }

    CJNIEXPORT jstring JNICALL
    Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1getHelloWorld(
            JNIEnv *jniEnv, jobject /*this*/, jlong nativeRef) {
        try {
            DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
            const auto &ref = ::djinni::objectFromHandleAddress<::TEST::TestISayHello>(nativeRef);
            auto r = ref->get_hello_world();
            return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
    }

    CJNIEXPORT void JNICALL
    Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1addSayHelloListener(
            JNIEnv *jniEnv, jobject /*this*/, jlong nativeRef, jlong j_listener) {
        try {
            DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
            const auto &ref = ::djinni::objectFromHandleAddress<::TEST::TestISayHello>(nativeRef);
            ref->addSayHelloListener(::djinni::I64::toCpp(jniEnv, j_listener));
        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
    }

    CJNIEXPORT void JNICALL
    Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1removeSayHelloListener(
            JNIEnv *jniEnv, jobject /*this*/, jlong nativeRef, jboolean j_listener) {
        try {
            DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
            const auto &ref = ::djinni::objectFromHandleAddress<::TEST::TestISayHello>(nativeRef);
            ref->removeSayHelloListener(::djinni::Bool::toCpp(jniEnv, j_listener));
        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
    }

    CJNIEXPORT void JNICALL
    Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1sayHello(JNIEnv *jniEnv,
                                                                                   jobject /*this*/,
                                                                                   jlong nativeRef,
                                                                                   jstring j_from,
                                                                                   jstring j_to) {
        try {
            DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
            const auto &ref = ::djinni::objectFromHandleAddress<::TEST::TestISayHello>(nativeRef);
            ref->sayHello(::djinni::String::toCpp(jniEnv, j_from),
                          ::djinni::String::toCpp(jniEnv, j_to));
        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
    }

}  // namespace djinni_generated

extern "C"
JNIEXPORT jobject JNICALL
Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_newInstance(JNIEnv *env,
                                                                          jclass clazz) {
    // TODO: implement newInstance()
    __android_log_print(ANDROID_LOG_ERROR, "RRR:: ", "%s", "NewInstance Implementation 2");
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::TEST::TestISayHello::newInstance();
        __android_log_print(ANDROID_LOG_ERROR, "RRR::: ", "%s", "NewInstance Implementation 3");
        return ::djinni::release(::djinni_generated::ISayHello::fromCpp(env, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(env, 0 /* value doesn't matter */)
}