// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

declare class NodeISayHello
{
    static declare function NewInstance(): NodeISayHello;
    declare function get_hello_world(): string;
    declare function addSayHelloListener(listener: number);
    declare function removeSayHelloListener(listener: boolean);
    declare function sayHello(from: string, to: string);
}
