// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#include "header/ISayHello.h"  // my header
#include "header/MyRecord.h"

namespace test {
    namespace hello {
        int32_t constexpr ISayHello::VERSION;
    }
}  // namespace test::hello
