// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include "support_lib/include/jni/djinni_support.hpp"
#include "header/Gender.h"

namespace djinni_generated {

    class JNIGender final : ::djinni::JniEnum {
    public:
        using CppType = ::test::hello::Gender;
        using JniType = jobject;

        using Boxed = JNIGender;

        static CppType toCpp(JNIEnv *jniEnv, JniType j) {
            return static_cast<CppType>(::djinni::JniClass<JNIGender>::get().ordinal(jniEnv, j));
        }

        static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, CppType c) {
            return ::djinni::JniClass<JNIGender>::get().create(jniEnv, static_cast<jint>(c));
        }

    private:
        JNIGender() : JniEnum("com/ruturaj/huawei/isayhello/Gender") {}

        friend ::djinni::JniClass<JNIGender>;
    };

}  // namespace djinni_generated
