// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#include "JNIISayHello.h"  // my header
#include "JNIMyRecord.h"
#include "support_lib/include/jni/Marshal.hpp"

namespace djinni_generated {

    JNIISayHello::JNIISayHello() : ::djinni::JniInterface<::test::hello::ISayHello, JNIISayHello>(
            "com/ruturaj/huawei/isayhello/ISayHello$CppProxy") {}

    JNIISayHello::~JNIISayHello() = default;


    CJNIEXPORT void JNICALL
    Java_com_ruturaj_huawei_isayhello_ISayHello_00024CppProxy_nativeDestroy(JNIEnv *jniEnv,
                                                                            jobject /*this*/,
                                                                            jlong nativeRef) {
        try {
            DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
            delete reinterpret_cast<::djinni::CppProxyHandle<::test::hello::ISayHello> *>(nativeRef);
        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
    }
/*
extern "C"*/ CJNIEXPORT jstring
    Java_com_ruturaj_huawei_isayhello_ISayHello_00024CppProxy_native_1sayHello(JNIEnv *jniEnv,
                                                                               jobject /*this*/,
                                                                               jlong nativeRef,
                                                                               jobject j_testInfo) {
        try {
            DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
            const auto &ref = ::djinni::objectFromHandleAddress<::test::hello::ISayHello>(
                    nativeRef);
            auto r = ref->sayHello(::djinni_generated::JNIMyRecord::toCpp(jniEnv, j_testInfo));
            return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
    }

/*extern "C" */CJNIEXPORT jobject
    Java_com_ruturaj_huawei_isayhello_ISayHello_00024CppProxy_newInstance(JNIEnv *jniEnv,
                                                                          jclass clazz) {
        try {
            DJINNI_FUNCTION_PROLOGUE0(jniEnv);
            auto r = ::test::hello::ISayHello::NewInstance();
            return ::djinni::release(::djinni_generated::JNIISayHello::fromCpp(jniEnv, r));
        } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
    }

}  // namespace djinni_generated
