// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include "support_lib/include/jni/djinni_support.hpp"
#include "header/ISayHello.h"

namespace djinni_generated {

    class JNIISayHello final
            : ::djinni::JniInterface<::test::hello::ISayHello, JNIISayHello> {
    public:
        using CppType = std::shared_ptr<::test::hello::ISayHello>;
        using CppOptType = std::shared_ptr<::test::hello::ISayHello>;
        using JniType = jobject;

        using Boxed = JNIISayHello;

        ~JNIISayHello();

        static CppType toCpp(JNIEnv *jniEnv, JniType j) {
            return ::djinni::JniClass<JNIISayHello>::get()._fromJava(jniEnv, j);
        }

        static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) {
            return {jniEnv, ::djinni::JniClass<JNIISayHello>::get()._toJava(jniEnv, c)};
        }

        static ::djinni::LocalRef<JniType>
        fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv, c); }

    private:
        JNIISayHello();

        friend ::djinni::JniClass<JNIISayHello>;
        friend ::djinni::JniInterface<::test::hello::ISayHello, JNIISayHello>;

    };

}  // namespace djinni_generated
