// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include <functional>

namespace test { namespace hello {

enum class SexModeEnum : int {
    SEX_MAN,
    SEX_WOMAN,
};

} }  // namespace test::hello

namespace std {

template <>
struct hash<::test::hello::SexModeEnum> {
    size_t operator()(::test::hello::SexModeEnum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
