// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <stdint.h>

namespace test {
    namespace hello {

        struct TestInfoStore;

        class TestDjnniInterface {
        public:
            virtual ~TestDjnniInterface() {}

            static constexpr int32_t VERSION = 1;

            virtual std::string Show(const TestInfoStore &testInfo) = 0;

            static std::shared_ptr<TestDjnniInterface> NewInstance();
        };

    }
}  // namespace test::hello
