// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from say_hello_world.djinni

#include "ISayHello.hpp"  // my header
#include "Marshal.hpp"
#include <android/log.h>
#include <cinttypes>

//namespace djinni_generated {

ISayHello::ISayHello() : ::djinni::JniInterface<::ISayHello, ISayHello>(
        "com/ruturaj/huawei/sayhelloworld/ISayHello$CppProxy") {}

void ISayHello::addSayHelloListener(int64_t listener) {
    __android_log_print(ANDROID_LOG_DEBUG, "RRR: ", "%" PRId64, listener);
}

void ISayHello::removeSayHelloListener(bool listener) {
    __android_log_print(ANDROID_LOG_DEBUG, "RRR: ", "%s", listener ? "true" : "false");
}

void ISayHello::sayHello(const std::string &from, const std::string &to) {
    __android_log_print(ANDROID_LOG_DEBUG, "RRR: ", "%s", (from + " " + to).c_str());
}

ISayHello::~ISayHello() = default;


CJNIEXPORT void JNICALL
Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_nativeDestroy(JNIEnv *jniEnv,
                                                                            jobject /*this*/,
                                                                            jlong nativeRef) {
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ISayHello> *>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
}

CJNIEXPORT void JNICALL
Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1addSayHelloListener(
        JNIEnv *jniEnv, jobject /*this*/, jlong nativeRef, jlong j_listener) {
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto &ref = ::djinni::objectFromHandleAddress<::ISayHello>(nativeRef);
        ref->addSayHelloListener(::djinni::I64::toCpp(jniEnv, j_listener));
        __android_log_print(ANDROID_LOG_DEBUG, "RRR: ", "%" PRId64, j_listener);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
}

CJNIEXPORT void JNICALL
Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1removeSayHelloListener(
        JNIEnv *jniEnv, jobject /*this*/, jlong nativeRef, jboolean j_listener) {
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto &ref = ::djinni::objectFromHandleAddress<::ISayHello>(nativeRef);
        ref->removeSayHelloListener(::djinni::Bool::toCpp(jniEnv, j_listener));
        __android_log_print(ANDROID_LOG_DEBUG, "RRR: ", "%s", j_listener ? "true" : "false");
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
}

CJNIEXPORT void JNICALL
Java_com_ruturaj_huawei_sayhelloworld_ISayHello_00024CppProxy_native_1sayHello(JNIEnv *jniEnv,
                                                                               jobject /*this*/,
                                                                               jlong nativeRef,
                                                                               jstring j_from,
                                                                               jstring j_to) {
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto &ref = ::djinni::objectFromHandleAddress<::ISayHello>(nativeRef);
        ref->sayHello(::djinni::String::toCpp(jniEnv, j_from),
                      ::djinni::String::toCpp(jniEnv, j_to));
        __android_log_print(ANDROID_LOG_DEBUG, "RRR: ", "%s", (std::string(
                reinterpret_cast<const char *>(j_from)) + " " + std::string(
                reinterpret_cast<const char *>(j_to))).c_str());
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv,)
}

//}  // namespace djinni_generated