package com.ruturaj.huawei.isayhello;// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ISayHello {
    public static final int VERSION = 1;

    public abstract String sayHello(MyRecord testInfo);

    public static ISayHello newInstance() {
        return CppProxy.newInstance();
    }

    private static final class CppProxy extends ISayHello {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef) {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);

        public void _djinni_private_destroy() {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }

        protected void finalize() throws Throwable {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public String sayHello(MyRecord testInfo) {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_sayHello(this.nativeRef, testInfo);
        }

        private native String native_sayHello(long _nativeRef, MyRecord testInfo);

        public static native ISayHello newInstance();
    }
}
