package com.ruturaj.huawei.isayhello;// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

import androidx.annotation.NonNull;

public final class MyRecord {
    /*package*/ final int id;

    /*package*/ final String name;

    /*package*/ final String project;

    /*package*/ final Gender sex;

    public MyRecord(
            int id,
            String name,
            String project,
            Gender sex) {
        this.id = id;
        this.name = name;
        this.project = project;
        this.sex = sex;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getProject() {
        return project;
    }

    public Gender getSex() {
        return sex;
    }

    @Override
    public String toString() {
        return "com.ruturaj.huawei.isayhello.MyRecord{" +
                "id=" + id +
                "," + "name=" + name +
                "," + "project=" + project +
                "," + "sex=" + sex +
                "}";
    }

}
