// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from say_hello_world.djinni

#ifndef DJINNI_GENERATED_ISAYHELLO_HPP
#define DJINNI_GENERATED_ISAYHELLO_HPP

#include <cstdint>
#include <memory>
#include <string>

namespace TEST {

class ISayHello {
public:
    virtual ~ISayHello() {}

    static std::shared_ptr<ISayHello> newInstance();

    virtual std::string get_hello_world() = 0;

    virtual void addSayHelloListener(int64_t listener) = 0;

    virtual void removeSayHelloListener(bool listener) = 0;

    virtual void sayHello(const std::string & from, const std::string & to) = 0;
};

}  // namespace TEST
#endif //DJINNI_GENERATED_ISAYHELLO_HPP
