//#include <jni.h>
//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from say_hello_world.djinni
//
//#include "ISayHello_.hpp"  // my header
////#include "Marshal.hpp"
////#include <jni.h>
//
////namespace djinni_generated {
////
////ISayHello_::ISayHello_() : ::JniInterface<::ISayHello_, ISayHello_>("com/example/jnigenpackage/ISayHello_$CppProxy") {}
////
////ISayHello_::ISayHello__() = default;
//
//ISayHello_::ISayHello__() = default;
//
//ISayHello_::ISayHello_() {
//
//}
//
//CJNIEXPORT void JNICALL Java_com_example_jnigenpackage_ISayHello_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
//{
//    try {
////        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        delete reinterpret_cast<::CppProxyHandle<::ISayHello_>*>(nativeRef);
//    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
//}
//
//CJNIEXPORT jobject JNICALL Java_com_example_jnigenpackage_ISayHello_get(JNIEnv* jniEnv, jobject /*this*/)
//{
//    try {
////        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
//        auto r = ::ISayHello_::get();
//        return ::release(_generated::ISayHello_::fromCpp(jniEnv, r));
//    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
//}
//
//CJNIEXPORT void JNICALL Java_com_example_jnigenpackage_ISayHello_00024CppProxy_native_1addSayHelloListener(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jlong j_listener)
//{
//    try {
////        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        const auto& ref = ::objectFromHandleAddress<::ISayHello_>(nativeRef);
//        ref->addSayHelloListener(::I64::toCpp(jniEnv, j_listener));
//    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
//}
//
//CJNIEXPORT void JNICALL Java_com_example_jnigenpackage_ISayHello_00024CppProxy_native_1removeSayHelloListener(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jboolean j_listener)
//{
//    try {
////        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        const auto& ref = ::objectFromHandleAddress<::ISayHello_>(nativeRef);
//        ref->removeSayHelloListener(::Bool::toCpp(jniEnv, j_listener));
//    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
//}
//
//CJNIEXPORT void JNICALL Java_com_example_jnigenpackage_ISayHello_00024CppProxy_native_1sayHello(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_from, jstring j_to)
//{
//    try {
////        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
//        const auto& ref = ::objectFromHandleAddress<::ISayHello_>(nativeRef);
//        ref->sayHello(::String::toCpp(jniEnv, j_from),
//                      ::String::toCpp(jniEnv, j_to));
//    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
//}
//
////}  // namespace djinni_generated


