//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from say_hello_world.djinni
//
//#ifndef DJINNI_GENERATED_ISAYHELLO_HPP_JNI_
//#define DJINNI_GENERATED_ISAYHELLO_HPP_JNI_
//
//#include <cassert>
//#include <mutex>
//#include "ISayHello_.hpp"
//#include "djinni_support.hpp"
//#include <jni.h>
//#include <string>
//#include <typeindex>
////#include "utils.hpp"
//#include <cassert>
//#include <exception>
//#include <memory>
//#include <mutex>
//#include <string>
//#include <vector>
//
//#define CJNIEXPORT extern "C" JNIEXPORT
//
//#define DJINNI_FUNCTION_PROLOGUE0(env_)
//#define DJINNI_FUNCTION_PROLOGUE1(env_, arg1_)
//
//void jniSetPendingFromCurrent(JNIEnv *env, const char *ctx) noexcept;
//
//#define JNI_TRANSLATE_EXCEPTIONS_RETURN(env, ret) \
//    catch (const std::exception &) { \
//        ::jniSetPendingFromCurrent(env, __func__); \
//        return ret; \
//    }
//
////namespace djinni_generated {
//
//void jniExceptionCheck(JNIEnv *env);
//
//JNIEnv *jniGetThreadEnv();
//
//struct GlobalRefDeleter {
//    void operator()(jobject globalRef) noexcept;
//};
//
//template<typename PointerType>
//class GlobalRef : public std::unique_ptr<typename std::remove_pointer<PointerType>::type,
//        GlobalRefDeleter> {
//public:
//    GlobalRef() {}
//
//    GlobalRef(GlobalRef &&obj)
//            : std::unique_ptr<typename std::remove_pointer<PointerType>::type, ::GlobalRefDeleter>(
//            std::move(obj)
//    ) {}
//
//    GlobalRef(JNIEnv *env, PointerType localRef)
//            : std::unique_ptr<typename std::remove_pointer<PointerType>::type, ::GlobalRefDeleter>(
//            static_cast<PointerType>(env->NewGlobalRef(localRef)),
//            ::GlobalRefDeleter{}
//    ) {}
//};
//
//template<typename T> using JavaProxyHandle = GlobalRef<jobject>;
//
//struct LocalRefDeleter {
//    void operator()(jobject localRef) noexcept;
//};
//
//template<typename PointerType>
//class LocalRef : public std::unique_ptr<typename std::remove_pointer<PointerType>::type,
//        LocalRefDeleter> {
//public:
//    LocalRef() {}
//
//    LocalRef(JNIEnv * /*env*/, PointerType localRef)
//            : std::unique_ptr<typename std::remove_pointer<PointerType>::type, ::LocalRefDeleter>(
//            localRef) {}
//
//    explicit LocalRef(PointerType localRef)
//            : std::unique_ptr<typename std::remove_pointer<PointerType>::type, LocalRefDeleter>(
//            localRef) {}
//
//    // Allow implicit conversion to PointerType so it can be passed
//    // as argument to JNI functions expecting PointerType.
//    // All functions creating new local references should return LocalRef instead of PointerType
//    operator PointerType() const & { return this->get(); }
//
//    operator PointerType() && = delete;
//};
//
//template<class T>
//const T &get(const T &x) noexcept { return x; }
//
//template<class T>
//typename LocalRef<T>::pointer get(const LocalRef<T> &x) noexcept { return x.get(); }
//
//template<class T>
//const T &release(const T &x) noexcept { return x; }
//
//template<class T>
//typename LocalRef<T>::pointer release(LocalRef<T> &x) noexcept { return x.release(); }
//
//template<class T>
//typename LocalRef<T>::pointer release(LocalRef<T> &&x) noexcept { return x.release(); }
//
//class JniClassInitializer {
//
//    using registration_vec = std::vector<std::function<void()>>;
//
//    static registration_vec get_all();
//
//private:
//
//    template<class C> friend
//    class JniClass;
//
//    friend void jniInit(JavaVM *);
//
//    static registration_vec &get_vec();
//
//    static std::mutex &get_mutex();
//
//public:
//    JniClassInitializer(std::function<void()> init);
//};
//
//template<class C>
//class JniClass {
//public:
//    static const C &get() {
//        (void) s_initializer; // ensure that initializer is actually instantiated
//        assert(s_singleton);
//        return *s_singleton;
//    }
//
//private:
//    static const JniClassInitializer s_initializer;
//    static std::unique_ptr<C> s_singleton;
//
//    static void allocate() {
//        // We can't use make_unique here, because C will have a private constructor and
//        // list JniClass as a friend; so we have to allocate it by hand.
//        s_singleton = std::unique_ptr<C>(new C());
//    }
//};
//
//struct CppProxyClassInfo {
//    const jclass clazz;
//    const jmethodID constructor;
//    const jfieldID idField;
//
//    CppProxyClassInfo(const char *className);
//
//    CppProxyClassInfo();
//
//    ~CppProxyClassInfo();
//
//    // Validity check
//    explicit operator bool() const { return bool(clazz); }
//};
//
//template<typename T>
//static inline auto get_unowning(const T &ptr) -> decltype(ptr.get()) {
//    return ptr.get();
//}
//
//template<typename T>
//static inline T *get_unowning(T *ptr) { return ptr; }
//
//template<typename Traits>
//class ProxyCache {
//public:
//    using UnowningImplPointer = typename Traits::UnowningImplPointer;
//    using OwningImplPointer = typename Traits::OwningImplPointer;
//    using OwningProxyPointer = typename Traits::OwningProxyPointer;
//    using WeakProxyPointer = typename Traits::WeakProxyPointer;
//    using UnowningImplPointerHash = typename Traits::UnowningImplPointerHash;
//    using UnowningImplPointerEqual = typename Traits::UnowningImplPointerEqual;
//
//    class Pimpl;
//
//    template<typename T, typename TagType = T>
//    class Handle {
//    public:
//        template<typename... Args>
//        Handle(Args &&... args)
//                : m_cache(get_base()), m_obj(std::forward<Args>(args)...) {}
//
//        Handle(const Handle &) = delete;
//
//        Handle &operator=(const Handle &) = delete;
//
//        ~Handle() { if (m_obj) cleanup(m_cache, typeid(TagType), get_unowning(m_obj), true); }
//
//        void assign(const T &obj) { m_obj = obj; }
//
//        const T &get() const & noexcept { return m_obj; }
//
//    private:
//        const std::shared_ptr<Pimpl> m_cache;
//        T m_obj;
//    };
//
//    using AllocatorFunction =
//            std::pair<OwningProxyPointer, UnowningImplPointer>(const OwningImplPointer &);
//
//    static OwningProxyPointer get(const std::type_index &,
//                                  const OwningImplPointer &impl,
//                                  AllocatorFunction *alloc);
//
//private:
//    static void cleanup(const std::shared_ptr<Pimpl> &,
//                        const std::type_index &,
//                        UnowningImplPointer,
//                        bool force_kill);
//
//    static const std::shared_ptr<Pimpl> &get_base();
//};
//
//struct JavaIdentityHash;
//struct JavaIdentityEquals;
//struct JavaProxyCacheTraits {
//    using UnowningImplPointer = jobject;
//    using OwningImplPointer = jobject;
//    using OwningProxyPointer = std::shared_ptr<void>;
//    using WeakProxyPointer = std::weak_ptr<void>;
//    using UnowningImplPointerHash = JavaIdentityHash;
//    using UnowningImplPointerEqual = JavaIdentityEquals;
//};
//
//extern template
//class ProxyCache<JavaProxyCacheTraits>;
//
//using JavaProxyCache = ProxyCache<JavaProxyCacheTraits>;
//template<typename T> using JavaProxyHandle = JavaProxyCache::Handle<GlobalRef<jobject>, T>;
//
//class JavaWeakRef;
//
//struct JniCppProxyCacheTraits {
//    using UnowningImplPointer = void *;
//    using OwningImplPointer = std::shared_ptr<void>;
//    using OwningProxyPointer = jobject;
//    using WeakProxyPointer = JavaWeakRef;
//    using UnowningImplPointerHash = std::hash<void *>;
//    using UnowningImplPointerEqual = std::equal_to<void *>;
//};
//
//extern template
//class ProxyCache<JniCppProxyCacheTraits>;
//
//using JniCppProxyCache = ProxyCache<JniCppProxyCacheTraits>;
//template<class T> using CppProxyHandle = JniCppProxyCache::Handle<std::shared_ptr<T>>;
//
//template<class T>
//static const std::shared_ptr<T> &objectFromHandleAddress(jlong handle) {
//    assert(handle);
//    assert(handle > 4096);
//    // Below line segfaults gcc-4.8. Using a temporary variable hides the bug.
//    //const auto & ret = reinterpret_cast<const CppProxyHandle<T> *>(handle)->get();
//    const CppProxyHandle<T> *proxy_handle =
//            reinterpret_cast<const CppProxyHandle<T> *>(handle);
//    const auto &ret = proxy_handle->get();
//    assert(ret);
//    return ret;
//}
//
//template<class I, class Self>
//class JniInterface {
//public:
//    jobject _toJava(JNIEnv *jniEnv, const std::shared_ptr<I> &c) const {
//
//        if (!c) {
//            return nullptr;
//        }
//
//        if (jobject impl = _unwrapJavaProxy<Self>(&c)) {
//            return jniEnv->NewLocalRef(impl);
//        }
//
//        assert(m_cppProxyClass);
//        return JniCppProxyCache::get(typeid(c), c, &newCppProxy);
//
//    }
//
//    std::shared_ptr<I> _fromJava(JNIEnv *jniEnv, jobject j) const {
//
//        if (!j) {
//            return nullptr;
//        }
//
//        if (m_cppProxyClass
//            && jniEnv->IsSameObject(jniEnv->GetObjectClass(j), m_cppProxyClass.clazz.get())) {
//            jlong handle = jniEnv->GetLongField(j, m_cppProxyClass.idField);
//            jniExceptionCheck(jniEnv);
//            return objectFromHandleAddress<I>(handle);
//        }
//
//        return _getJavaProxy<Self>(j);
//    }
//
//    JniInterface(const char *cppProxyClassName) : m_cppProxyClass(cppProxyClassName) {}
//
//    JniInterface() : m_cppProxyClass{} {}
//
//private:
//
//    static std::pair<jobject, void *> newCppProxy(const std::shared_ptr<void> &cppObj) {
//        const auto &data = JniClass<Self>::get();
//        const auto &jniEnv = jniGetThreadEnv();
//        std::unique_ptr<CppProxyHandle<I>> to_encapsulate(
//                new CppProxyHandle<I>(std::static_pointer_cast<I>(cppObj)));
//        jlong handle = static_cast<jlong>(reinterpret_cast<uintptr_t>(to_encapsulate.get()));
//        jobject cppProxy = jniEnv->NewObject(data.m_cppProxyClass.clazz.get(),
//                                             data.m_cppProxyClass.constructor,
//                                             handle);
//        jniExceptionCheck(jniEnv);
//        to_encapsulate.release();
//        return {cppProxy, cppObj.get()};
//    }
//
//    template<typename S, typename JavaProxy = typename S::JavaProxy>
//    jobject _unwrapJavaProxy(const std::shared_ptr<I> *c) const {
//        if (auto proxy = dynamic_cast<JavaProxy *>(c->get())) {
//            return proxy->template JavaProxyHandle<JavaProxy>::get().get();
//        } else {
//            return nullptr;
//        }
//    }
//
//    template<typename S>
//    jobject _unwrapJavaProxy(...) const {
//        return nullptr;
//    }
//
//    template<typename S, typename JavaProxy = typename S::JavaProxy>
//    std::shared_ptr<I> _getJavaProxy(jobject j) const {
//        static_assert(std::is_base_of<JavaProxyHandle<JavaProxy>, JavaProxy>::value,
//                      "JavaProxy must derive from JavaProxyCacheEntry");
//
//        return std::static_pointer_cast<JavaProxy>(JavaProxyCache::get(
//                typeid(JavaProxy), j,
//                [](const jobject &obj) -> std::pair<std::shared_ptr<void>, jobject> {
//                    auto ret = std::make_shared<JavaProxy>(obj);
//                    return {ret, ret->JavaProxyHandle<JavaProxy>::get().get()};
//                }
//        ));
//    }
//
//    template<typename S>
//    std::shared_ptr<I> _getJavaProxy(...) const {
//        assert(false);
//        return nullptr;
//    }
//
//    const CppProxyClassInfo m_cppProxyClass;
//};
//
//class ISayHello_ final : ::JniInterface<::ISayHello_, ISayHello_> {
//public:
//    using CppType = std::shared_ptr<::ISayHello_>;
//    using CppOptType = std::shared_ptr<::ISayHello_>;
//    using JniType = jobject;
//
//    using Boxed = ISayHello_;
//
//    ~ISayHello_();
//
//    static CppType toCpp(JNIEnv *jniEnv, JniType j) {
//        return ::JniClass<ISayHello_>::get()._fromJava(jniEnv, j);
//    }
//
//    static ::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) {
//        return {jniEnv, ::JniClass<ISayHello_>::get()._toJava(jniEnv, c)};
//    }
//
//    static ::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) {
//        return fromCppOpt(jniEnv, c);
//    }
//
//    virtual void addSayHelloListener(int64_t listener) = 0;
//
//    virtual void removeSayHelloListener(bool listener) = 0;
//
//    virtual void sayHello(const std::string &from, const std::string &to) = 0;
//
//private:
//    ISayHello_();
//
//    friend ::JniClass<ISayHello_>;
//    friend ::JniInterface<::ISayHello_, ISayHello_>;
//
//};
//
////}  // namespace djinni_generated
//#endif //DJINNI_GENERATED_ISAYHELLO_HPP_JNI_