// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from say_hello_world.djinni

package com.ruturaj.huawei.sayhelloworld;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ISayHello {
    public abstract String getHelloWorld();

    public abstract void addSayHelloListener(long listener);

    public abstract void removeSayHelloListener(boolean listener);

    public abstract void sayHello(String from, String to);
    /** Release the underlying native object */
    public abstract void destroy();


    public static native ISayHello NewInstance();

    private static final class CppProxy extends ISayHello
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        @Override
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String getHelloWorld()
        {
            if (this.destroyed.get())
            {
                throw new RuntimeException("trying to use a destroyed object (ISayHello)");
            }
            return native_getHelloWorld(this.nativeRef);
        }
        private native String native_getHelloWorld(long _nativeRef);

        @Override
        public void addSayHelloListener(long listener)
        {
            if (this.destroyed.get())
            {
                throw new RuntimeException("trying to use a destroyed object (ISayHello)");
            }
            native_addSayHelloListener(this.nativeRef, listener);
        }
        private native void native_addSayHelloListener(long _nativeRef, long listener);

        @Override
        public void removeSayHelloListener(boolean listener)
        {
            if (this.destroyed.get())
            {
                throw new RuntimeException("trying to use a destroyed object (ISayHello)");
            }
            native_removeSayHelloListener(this.nativeRef, listener);
        }
        private native void native_removeSayHelloListener(long _nativeRef, boolean listener);

        @Override
        public void sayHello(String from, String to)
        {
            if (this.destroyed.get())
            {
                throw new RuntimeException("trying to use a destroyed object (ISayHello)");
            }
            native_sayHello(this.nativeRef, from, to);
        }
        private native void native_sayHello(long _nativeRef, String from, String to);
    }
}
