// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <stdint.h>

namespace test {
    namespace hello {

        struct MyRecord;

        class ISayHello {
        public:
            virtual ~ISayHello() {}

            static constexpr int32_t VERSION = 1;

            virtual std::string sayHello(const MyRecord &testInfo) = 0;

            static std::shared_ptr<ISayHello> NewInstance();
        };

    }
}  // namespace test::hello
