// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from say_hello_world.djinni

#ifndef DJINNI_GENERATED_ISAYHELLO_HPP_JNI_
#define DJINNI_GENERATED_ISAYHELLO_HPP_JNI_

#include "ISayHello.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class ISayHello final : ::djinni::JniInterface<::TEST::ISayHello, ISayHello> {
public:
    using CppType = std::shared_ptr<::TEST::ISayHello>;
    using CppOptType = std::shared_ptr<::TEST::ISayHello>;
    using JniType = jobject;

    using Boxed = ISayHello;

    ~ISayHello();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<ISayHello>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<ISayHello>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    ISayHello();
    friend ::djinni::JniClass<ISayHello>;
    friend ::djinni::JniInterface<::TEST::ISayHello, ISayHello>;

};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_ISAYHELLO_HPP_JNI_
