// Targeted by JavaCPP version 1.5.4: DO NOT EDIT THIS FILE

package com.example.myapplication;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class NativeLibrary extends com.example.myapplication.NativeLibraryConfig {
    static { Loader.load(); }

// Parsed from NativeLibrary.h

    // #include <string>
    @Namespace("NativeLibrary") public static class NativeClass extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public NativeClass() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public NativeClass(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public NativeClass(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public NativeClass position(long position) {
            return (NativeClass)super.position(position);
        }
        @Override public NativeClass getPointer(long i) {
            return new NativeClass(this).position(position + i);
        }

        public native @StdString BytePointer get_property();
        public native void set_property(@StdString BytePointer property);
        public native void set_property(@StdString String property);
        public native @StdString BytePointer property(); public native NativeClass property(BytePointer setter);

        public native @StdString BytePointer get_value();
        public native void set_value(@StdString BytePointer value);
        public native void set_value(@StdString String value);
        public native @StdString BytePointer value(); public native NativeClass value(BytePointer setter);

        public native int year(); public native NativeClass year(int setter);
        public native int get_year();
        public native void set_year(int year);

        public native int add(int a, int b);
    }

    @Namespace("NativeLibrary") @NoOffset public static class Foo extends Pointer {
        static { Loader.load(); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public Foo(Pointer p) { super(p); }

        public native int n(); public native Foo n(int setter);
        public Foo(int n) { super((Pointer)null); allocate(n); }
        private native void allocate(int n);
        public native int bar(int a, int b);
    }

    @Namespace("NativeLibrary") public static native int callback(Foo foo, int a, int b);





}
