//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from info.djinni
//
//#pragma once
//
//#include <functional>
//
//namespace test {
//    namespace hello {
//
//        enum class Gender : int {
//            Man,
//            Woman,
//        };
//
//    }
//}  // namespace test::hello
//
//namespace std {
//
//    template<>
//    struct hash<::test::hello::Gender> {
//        size_t operator()(::test::hello::Gender type) const {
//            return std::hash<int>()(static_cast<int>(type));
//        }
//    };
//
//}  // namespace std
