// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include "aki/jsbind.h"

namespace test {
namespace hello {

enum Gender {
    Man,
    Woman,
};

JSBIND_ENUM(Gender) {
    JSBIND_ENUM_VALUE(Man);
    JSBIND_ENUM_VALUE(Woman);
}
} // namespace hello
} // namespace test
