// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <stdint.h>
#include "aki/jsbind.h"

namespace test {
namespace hello {

class MyRecord;

class ISayHello
{
public:
    virtual ~ISayHello() {}

    static constexpr int32_t VERSION = 1;

    std::string sayHello(const MyRecord &testInfo);

    static std::shared_ptr<ISayHello> NewInstance();
};

} // namespace hello
} // namespace test
