// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from info.djinni

#pragma once

#include "Gender.h"
#include <cstdint>
#include <string>
#include <utility>
#include "aki/jsbind.h"

namespace test {
namespace hello {

class MyRecord
{
public:
    MyRecord() = default;

    int32_t id;
    std::string name;
    std::string project;
    Gender sex;

    MyRecord(int32_t id_, std::string name_, std::string project_, Gender sex_)
        : id(id_), name(std::move(name_)), project(std::move(project_)), sex(sex_) {}
};

JSBIND_CLASS(MyRecord) {
    JSBIND_CONSTRUCTOR<int32_t, std::string, std::string, Gender>();
    JSBIND_PROPERTY(id);
    JSBIND_PROPERTY(name);
    JSBIND_PROPERTY(project);
    JSBIND_PROPERTY(sex);
}

} // namespace hello
} // namespace test
