//// AUTOGENERATED FILE - DO NOT MODIFY!
//// This file generated by Djinni from info.djinni
//
//#pragma once
//
//#include "Gender.h"
//#include <cstdint>
//#include <string>
//#include <utility>
//
//namespace test {
//    namespace hello {
//
//        struct MyRecord final {
//            int32_t id;
//            std::string name;
//            std::string project;
//            Gender sex;
//
//            MyRecord(int32_t id_,
//                     std::string name_,
//                     std::string project_,
//                     Gender sex_)
//                    : id(std::move(id_)), name(std::move(name_)), project(std::move(project_)),
//                      sex(std::move(sex_)) {}
//        };
//
//    }
//}  // namespace test::hello
